#!/bin/bash

# The `.env` file at the root will be the source of truth used by all other packages (via symlinks).
ROOT_ENV_FILE="$(dirname "$0")/../.env"

if [ ! -f "$ROOT_ENV_FILE" ]; then
  echo "NODE_ENV=development" > "$ROOT_ENV_FILE"
  echo "DATABASE_URL=file:./droyds.db" >> "$ROOT_ENV_FILE"
  echo "Created .env file."
fi

PACKAGES=("src/core" "src/server" "src/bots" "src/website")

for pkg in "${PACKAGES[@]}"; do
  TARGET_DIR="$(realpath "$(dirname "$0")/../$pkg")"
  TARGET_ENV_FILE="$TARGET_DIR/.env"

  if [ ! -d "$TARGET_DIR" ]; then
    echo "Directory does not exist: $TARGET_DIR"
    continue
  fi

  if [ -e "$TARGET_ENV_FILE" ] || [ -L "$TARGET_ENV_FILE" ]; then
    rm "$TARGET_ENV_FILE"
  fi

  ln -s "$(realpath "$ROOT_ENV_FILE")" "$TARGET_ENV_FILE"
  echo "Symlink created: $TARGET_ENV_FILE"
done
